const express = require('express')
const router = express.Router()
const {viewMyInfo,searchForPatient,viewPatient,viewPatients,filterAppointments,editEmail, writePerscription}= require('../controllers/doctorController')
const {protect,checkRole} = require('../middleware/authMiddleware')
router.put('/editDocEmail',protect,checkRole('doctor'),editEmail)
router.get('/view-appointments',protect,checkRole('doctor'),filterAppointments)
router.get('/view-patients',protect,checkRole('doctor'),viewPatients)
router.get('/view-patient',protect,checkRole('doctor'),viewPatient)
router.get('/search',protect,checkRole('doctor'),searchForPatient)
router.post('/write-perscription',protect,checkRole('doctor'),writePerscription)
router.get('/view-my-info',protect,checkRole('doctor'),viewMyInfo)
module.exports = router